### ISSUE TITLE
Client Module

### ISSUE THREAD

**Issue by tosiek13** [tosiek13/enchat#9]
I think that you have some endless loop in your code.
I know that you need it to scan the buffer or sth.
But, could you (for example),  run it in Thread and sleep this thread for a while?
Cause, it's not necessary to use nearly 70% of processor.

As soon as possible, that's really annoying.

Thanks.

**Comment by bercik** [comment]
I add sleep for 100 nanoseconds in main loop in main.AppCore. This can be increased due to too much CPU usage, but as i checked it should be ok.
